# Site settings
title: Practice. Make. Perfect.
email: jheil@wooster.edu
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Jacob Heil, Mellon Digital Scholar for The Five Colleges of Ohio. The views expressed herein, however, are his own and not those of the Andrew W. Mellon Foundation nor of the Ohio Five. When writing, writing about: digital scholarship, humanities, project management, and pedagogy; liberal arts colleges and DH/DS; and possibly my dogs. 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://jacobheil.github.io/" # the base hostname & protocol for your site
twitter_username: "@dr_heil"
github_username:  "jacobheil"

# Build settings
markdown: kramdown
